### ISSUE TITLE
Not quite an issue, just a suggestion

### ISSUE THREAD

**Issue by float-mode** [distantnative/switch#2]
Using the plugin for the first time today, trying to see how it works and how I can use it. It's very cool, I like it... As a newbie tho, I thought there was a tiny bit more to it.

Here's what I mean. In the readme it's indicated that this is basically a dope-looking check box and it functions like such. What would make this out-of-this-world for me, if there was a way to keep 2 "text" lines in the Blueprints, like textOn and textOff and then (with CSS or somehow) to display one or the other based on the switch state... As you click it.. I mean that content you put in either one of the "text" lines in the blueprint is not really connected to anything else, other than which one is displayed and which one is hidden...

I'm not that advanced, and totally new to kirby too.. If I knew how I would have done it and would have been sending it to you right now :)

**Comment by distantnative** [comment]
Just added it to the newly released v0.4
